### PR TITLE
IC-11 feat: implement LearnWorlds ingestion client  #80 #81

### LINKED ISSUE #80: IC-11 feat: implement LearnWorlds ingestion client (auth + read-only fetch)
### Title
IC-11 feat: implement LearnWorlds ingestion client (auth + read-only fetch)

---

## Description
Build a production-safe LearnWorlds ingestion client that authenticates, fetches learner activity/progress data, and exposes ingestion execution paths for internal use. This issue explicitly excludes database schema work.

---

## Goals
- Authenticate with LearnWorlds using OAuth2  
- Fetch learner, course, and progress/activity data in read-only mode  
- Support internal execution modes:
  - On-demand trigger via internal endpoint  
  - Scheduled ingestion job  
- Enforce secure credential handling and sanitized logging  
- Add resilience for retries, timeouts, and rate limiting  

---

### LearnWorlds Client Service Layer
- Implement token acquisition and refresh flow  
- Implement authenticated request wrapper  
- Support required headers (including client-identification header if required by LearnWorlds)  
- Enforce HTTPS-only outbound calls  

### Ingestion Orchestrator
- Start and finish ingestion runs  
- Handle auth/fetch failures with controlled error responses  
- Produce structured logs without exposing credentials/secrets  

### Execution Entry Points
- Internal endpoint for manual trigger  
- Scheduled execution path  

---

## Non-Functional Requirements
- **Read-only guarantee:** no write/modify actions against LearnWorlds  
- **Reliability-first behavior:** retries with bounded backoff  
- **Rate-limit aware** request handling  
- **Observability:** clear operational logs and run outcome metadata  

---

### Scenario 1: Successful Fetch
**Given** valid credentials  
**When** ingestion is triggered  
**Then** learner progress/activity data is fetched successfully  

---

### Scenario 2: Auth Failure Handling
**Given** invalid credentials  
**When** ingestion is triggered  
**Then** the operation fails with a controlled error  
**And** logs do not expose secrets  

---

### Scenario 3: Read-Only Enforcement
**Given** ingestion executes  
**When** LearnWorlds API calls are made  
**Then** only read operations are performed  

---

### Scenario 4: Resilience and Retries
**Given** transient API failures or rate limiting  
**When** requests fail  
**Then** retry policy is applied  
**And** final status is recorded clearly  

---

### Scenario 5: Execution Consistency
**Given** on-demand and scheduled execution paths  
**When** either runs  
**Then** behavior is consistent and traceable  

---

## Implementation Notes
- Centralize HTTP client logic for reuse across ingestion flows  
- Use environment variables for credentials and configuration  
- Ensure logs redact sensitive fields (tokens, secrets)  
- Align retry/backoff strategy with project standards  

---

## Validation Checklist
- [ ] OAuth2 authentication flow works (token + refresh)  
- [ ] Read-only API calls verified against LearnWorlds endpoints  
- [ ] Retry/backoff mechanism implemented and tested  
- [ ] Logs are structured and do not leak sensitive information  
- [ ] Internal endpoint trigger works correctly  
- [ ] Scheduled job executes successfully  
- [ ] Linting and formatting checks pass

### LINKED ISSUE #81: # IC-12 test: add tests for LearnWorlds client auth failure + happy path
# IC -12 test: add tests for LearnWorlds client auth failure + happy path (mocked or actual data) 

## Description

Add automated tests for the LearnWorlds progress ingestion client covering both:

- Successful authentication and data retrieval (happy path)
- Authentication failure scenarios (401 / 403)

LearnWorlds API interactions might be mocked or actual data can be used 
---

### Happy Path ( Success)

-  LearnWorlds API success response
- Verify:
  - Response is parsed correctly
  - Data maps into expected raw internal structure
  - No unexpected side effects occur

### Auth Failure (Mocked 401 / 403)

-  LearnWorlds API returning 401 or 403
- Verify:
  - Controlled error is returned
  - System does not crash
  - No credentials are logged
  - Failure is logged appropriately

---
### Scenario 1 — Successful Ingestion

**Given** a  LearnWorlds API(mocked) success response  
**When** ingestion runs  
**Then** data is parsed into the expected raw structure  

---

### Scenario 2 — Authentication Failure

**Given** a 401 or 403 response from LearnWorlds  
**When** ingestion runs  
**Then** the system returns a controlled error  
**And** the application does not crash  

---

### PR DESCRIPTION
**Pull request by sserurich**
### Title
IC-11 feat: implement LearnWorlds ingestion client and admin trigger endpoint

---

## Summary
This PR implements IC-11 by adding a secure, read-only LearnWorlds ingestion client and an internal admin-triggered ingestion endpoint, with Playwright coverage for endpoint auth and validation behavior.

---

## Related Issue
Closes IC-11 
Closes IC-12 

---

### LearnWorlds Client Service
- OAuth2 client-credentials token flow  
- HTTPS-only configuration validation  
- Required request headers support (`Authorization`, `Lw-Client`)  
- Timeout handling  
- Retry/backoff behavior for transient failures and rate limiting  

### Ingestion Orchestrator
- Creates sync run records  
- Fetches LearnWorlds progress/activity data  
- Stores raw payload records for traceability  
- Updates sync run status and safe error messages  

### Internal Admin Endpoint
- `POST /api/admin/learnworlds/ingest`  
- Admin-only access check  
- Trigger mode validation (`manual`, `scheduled`, `webhook`)  
- Controlled error responses for config/auth/fetch failures  

### Playwright Tests
- Unauthenticated flow (redirect to login via middleware)  
- Authenticated non-admin returns unauthorized  
- Admin invalid trigger mode returns bad request  
- Admin manual trigger returns controlled success/failure response shape  

### Test Utility Refactor
- Extracted user provisioning into `create-test-user` utility  

---

## Why This Change
This establishes a reliable, secure IC-11 ingestion foundation that reads from LearnWorlds only and persists ingestion metadata for downstream processing (IC-13+), while keeping authentication and operational failures controlled and observable.

---

## Validation
- New Playwright spec passes locally after environment setup  
- Lint/type checks for new files pass  
- Endpoint behavior aligns with current middleware redirect model for unauthenticated requests  

---

## Notes
- API remains read-only against LearnWorlds  
- Current unauthenticated API expectation is redirect (middleware behavior), not direct JSON 401  
- Uses existing sync and raw staging tables introduced in prior schema phase  

---

### Functionality
- [ ] Ingestion client authenticates and fetches data correctly  
- [ ] Admin endpoint triggers ingestion successfully  
- [ ] Trigger mode validation works as expected  

### Security
- [ ] Admin-only access enforced correctly  
- [ ] No secrets exposed in logs  
- [ ] HTTPS enforced for outbound calls  

### Reliability
- [ ] Retry/backoff logic handles transient failures  
- [ ] Timeout handling works correctly  
- [ ] Controlled error responses returned  

### Testing
- [ ] Playwright tests pass locally  
- [ ] Auth flows (unauthenticated, non-admin, admin) behave correctly  
- [ ] Success/failure response shapes are consistent  

### Code Quality
- [ ] Code follows project conventions  
- [ ] No TypeScript errors  

### CI / Formatting
- [ ] Prettier passes
- [ ] Linting passes
- [ ] GitHub Actions checks are green

### CODE REVIEW

File: lib/learnworlds/ingestion.ts [hunk 1]
```diff
@@ -0,0 +1,124 @@
...
+          progressPercentage: toBoundedProgress(record.progressPercentage),
+          lastActivityTimestamp: toTimestampOrNull(record.lastActivityTimestamp),
+          recordHash: hashRecord(record),
+          payload: record.raw,
+          receivedAt: new Date().toISOString(),
+        }))
+      );
+    }
+
+    const totalRecords = fetched.records.length;
```
Comment (nsoliven) [inline lib/learnworlds/ingestion.ts]: invalidRecords is always 0 here because records that failed normalization (missing learnerId/courseId) were already filtered out in client.ts before reaching this function. The pre-filter count (rawRecords.length) isn't propagated through LearnworldsFetchResponse, so there's no way to compute the real invalid count. If this is intentional as a v1 placeholder for IC-13, worth adding a comment. Otherwise consider threading rawCount through so the sync run log reflects the actual numbers.

**Review by nsoliven — COMMENTED** [review]
Well-structured code + error handling, retry backoff, HTTPS enforcement, and credential management are all solid. One thing to watch: the record counting in ingestion.ts won't surface dropped records since filtering happens upstream in client.ts and the count is lost.

**Review by Connor-Palmira — COMMENTED** [review]
The code is well structured and has a very reliable foundation. There is also really good error handling that make it clear when and how something went wrong. As stated before, in `lib/learnworlds/ingestion.ts`: line 85, `totalRecords` is effectively 0 in this context due to the filtering via `normalizeProgressRecord`, intentional or not. This is worth noting if this is an error or a placeholder as this will impact logic.

Overall, solid implementation that handles retry backoff with the `fetchWithRetries` function really well. You also provide comprehensive testing really well as well as good error handling.

**Review by zsin520 — COMMENTED** [review]
Hi Richard, I am reviewing since this code is also important for the recommendation engine. 

## Failed ingestions
A failed status is recorded in `learnworlds_sync_runs`, but there is notification. These failures could pile up in the table. For the recommendation model this means it could be running on stale data and missing important learner updates. I'm not sure if this should be updated here, or it could be another PR since there is technically no issues with this code. 

## Pagination
I am not sure how the LearnWorlds API works, but if it returns records split into pages then `fetchLearnworldsProgressData` will fail to get all the information after the first page. This would mean the recommendation engine cannot access valuable information for recommending to the user. I recommend a loop in the `fetchLearnworldsProgressData` function.

**Comment by bofengb** [comment]
# PR Review: `feature/learnworlds-ingestion-client`

Hey, thanks for putting this together. It's a solid foundation for the LearnWorlds ingestion pipeline. The error handling, retry logic with exponential backoff, and HTTPS enforcement are all well done. I've gone through the code alongside the existing reviews and want to flag two things.

---

## 1. The Goal

This PR addresses #80 and #81 (IC-11 / IC-12) by implementing a secure, read-only LearnWorlds ingestion client with an admin-triggered endpoint at `POST /api/admin/learnworlds/ingest`. It creates sync run records, fetches progress data via OAuth2 client credentials, normalizes and persists raw payloads, and includes Playwright coverage for the endpoint's auth and validation flows. It builds on the schema work in #97.

---

## 2. Issues

### 2.1 Record Counting Doesn't Reflect Reality

In `lib/learnworlds/client.ts` (lines 248-254), `fetchLearnworldsProgressData()` filters out invalid records before returning:

```typescript
const rawRecords = parseResponsePayload(rawPayload);
const records = rawRecords
    .map(normalizeProgressRecord)
    .filter((record): record is LearnworldsProgressRecord => record !== null);

return {
    records,          // ← only valid records survive
    endpoint: config.progressEndpoint,
    httpStatus: response.status,
};
```

`normalizeProgressRecord` returns `null` for any record missing a `learnerId` or `courseId`, and those are filtered out here. The pre-filter count (`rawRecords.length`) is available in scope but never propagated — `LearnworldsFetchResponse` in `types.ts` has no field for it.

Then in `lib/learnworlds/ingestion.ts` (lines 85-87):

```typescript
const totalRecords = fetched.records.length;
const validRecords = fetched.records.length;
const invalidRecords = 0;
```

Since `fetched.records` only contains valid records, `totalRecords` and `validRecords` are always identical, and `invalidRecords` is permanently `0`. The sync run log ends up painting a picture where 100% of records are valid every time, even if the API returned dozens of malformed entries.

This matters for observability. If #123 (health monitoring) consumes these fields, it can never detect data quality degradation. A fix would be to thread the raw count through `LearnworldsFetchResponse`:

```typescript
// types.ts
export interface LearnworldsFetchResponse {
  records: LearnworldsProgressRecord[];
  rawCount: number;        // total records before normalization
  endpoint: string;
  httpStatus: number;
}
```

Then in `client.ts`:
```typescript
return {
  records,
  rawCount: rawRecords.length,
  endpoint: config.progressEndpoint,
  httpStatus: response.status,
};
```

And in `ingestion.ts`:
```typescript
const totalRecords = fetched.rawCount;
const validRecords = fetched.records.length;
const invalidRecords = totalRecords - validRecords;
```

### 2.2 No Pagination Handling

`fetchLearnworldsProgressData()` in `client.ts` (line 237) makes a single GET request with no pagination parameters:

```typescript
const endpoint = `${config.apiBaseUrl}${config.progressEndpoint}`;
const response = await fetchWithRetries(
    endpoint,
    { method: 'GET', headers: { ... }, cache: 'no-store' },
    config.timeoutMs
);
```

The LearnWorlds API paginates list endpoints using `page` (1-based) and `per_page` query parameters, returning results in a `data` array. The code's `parseResponsePayload()` already handles the `data` array wrapper, which is consistent with this format, but without a pagination loop, everything beyond the first page is silently dropped. There's no indication in the response or the sync run record that data was missed.

For a data pipeline feeding a recommendation engine (IC-13, #99), silent data loss is a serious concern. I'd suggest either implementing a pagination loop or, at minimum, documenting this as a known limitation with a `// TODO` and a follow-up issue so it doesn't get lost.

File: lib/learnworlds/ingestion.ts (hunk 1 above)
Comment (sserurich) [reply lib/learnworlds/ingestion.ts]: Thanks  @nsoliven for the thoughtful review. You were right that invalid records were invisible in sync-run metrics. We fixed this by threading pre-normalization totals through the fetch response:

- Added `rawCount` to the response contract in `types.ts`
- Returned `rawCount` from `client.ts`
- Updated `ingestion.ts` to compute:
  - `totalRecords = rawCount`
  - `validRecords = normalized.length`
  - `invalidRecords = total - valid`

This now reflects dropped/invalid upstream records correctly.

**Comment by sserurich** [comment]
> The code is well structured and has a very reliable foundation. There is also really good error handling that make it clear when and how something went wrong. As stated before, in `lib/learnworlds/ingestion.ts`: line 85, `totalRecords` is effectively 0 in this context due to the filtering via `normalizeProgressRecord`, intentional or not. This is worth noting if this is an error or a placeholder as this will impact logic.
> 
> Overall, solid implementation that handles retry backoff with the `fetchWithRetries` function really well. You also provide comprehensive testing really well as well as good error handling.

Great catch @Connor-Palmira on the counting logic around ingestion totals. Confirmed and addressed. We now distinguish raw records vs normalized valid records end-to-end:

- `rawCount` added to fetch response in `types.ts`
- `rawCount` populated in `client.ts`
- Sync-run count fields corrected in `ingestion.ts`

So totals now represent reality, instead of implying 100% validity by construction.

**Comment by sserurich** [comment]
> Hi Richard, I am reviewing since this code is also important for the recommendation engine.
> 
> ## Failed ingestions
> A failed status is recorded in `learnworlds_sync_runs`, but there is notification. These failures could pile up in the table. For the recommendation model this means it could be running on stale data and missing important learner updates. I'm not sure if this should be updated here, or it could be another PR since there is technically no issues with this code.
> 
> ## Pagination
> I am not sure how the LearnWorlds API works, but if it returns records split into pages then `fetchLearnworldsProgressData` will fail to get all the information after the first page. This would mean the recommendation engine cannot access valuable information for recommending to the user. I recommend a loop in the `fetchLearnworldsProgressData` function.

Thanks @zsin520 , both concerns were valid and I addressed them.

- **Pagination:** Implemented in `client.ts` using `page + per_page`, with stop-on-short-page and max-page safety guard.
- **Failed ingestion visibility:** Added a lightweight, best-effort webhook notification hook in `ingestion.ts`, configurable via:
  - `LEARNWORLDS_FAILURE_WEBHOOK_URL`
  - `LEARNWORLDS_FAILURE_NOTIFY_TIMEOUT_MS`

No configured webhook means no-op, so behavior remains safe by default.

**Comment by sserurich** [comment]
> # PR Review: `feature/learnworlds-ingestion-client`
> Hey, thanks for putting this together. It's a solid foundation for the LearnWorlds ingestion pipeline. The error handling, retry logic with exponential backoff, and HTTPS enforcement are all well done. I've gone through the code alongside the existing reviews and want to flag two things.
> 
> ## 1. The Goal
> This PR addresses #80 and #81 (IC-11 / IC-12) by implementing a secure, read-only LearnWorlds ingestion client with an admin-triggered endpoint at `POST /api/admin/learnworlds/ingest`. It creates sync run records, fetches progress data via OAuth2 client credentials, normalizes and persists raw payloads, and includes Playwright coverage for the endpoint's auth and validation flows. It builds on the schema work in #97.
> 
> ## 2. Issues
> ### 2.1 Record Counting Doesn't Reflect Reality
> In `lib/learnworlds/client.ts` (lines 248-254), `fetchLearnworldsProgressData()` filters out invalid records before returning:
> 
> ```ts
> const rawRecords = parseResponsePayload(rawPayload);
> const records = rawRecords
>     .map(normalizeProgressRecord)
>     .filter((record): record is LearnworldsProgressRecord => record !== null);
> 
> return {
>     records,          // ← only valid records survive
>     endpoint: config.progressEndpoint,
>     httpStatus: response.status,
> };
> ```
> 
> `normalizeProgressRecord` returns `null` for any record missing a `learnerId` or `courseId`, and those are filtered out here. The pre-filter count (`rawRecords.length`) is available in scope but never propagated — `LearnworldsFetchResponse` in `types.ts` has no field for it.
> 
> Then in `lib/learnworlds/ingestion.ts` (lines 85-87):
> 
> ```ts
> const totalRecords = fetched.records.length;
> const validRecords = fetched.records.length;
> const invalidRecords = 0;
> ```
> 
> Since `fetched.records` only contains valid records, `totalRecords` and `validRecords` are always identical, and `invalidRecords` is permanently `0`. The sync run log ends up painting a picture where 100% of records are valid every time, even if the API returned dozens of malformed entries.
> 
> This matters for observability. If #123 (health monitoring) consumes these fields, it can never detect data quality degradation. A fix would be to thread the raw count through `LearnworldsFetchResponse`:
> 
> ```ts
> // types.ts
> export interface LearnworldsFetchResponse {
>   records: LearnworldsProgressRecord[];
>   rawCount: number;        // total records before normalization
>   endpoint: string;
>   httpStatus: number;
> }
> ```
> 
> Then in `client.ts`:
> 
> ```ts
> return {
>   records,
>   rawCount: rawRecords.length,
>   endpoint: config.progressEndpoint,
>   httpStatus: response.status,
> };
> ```
> 
> And in `ingestion.ts`:
> 
> ```ts
> const totalRecords = fetched.rawCount;
> const validRecords = fetched.records.length;
> const invalidRecords = totalRecords - validRecords;
> ```
> 
> ### 2.2 No Pagination Handling
> `fetchLearnworldsProgressData()` in `client.ts` (line 237) makes a single GET request with no pagination parameters:
> 
> ```ts
> const endpoint = `${config.apiBaseUrl}${config.progressEndpoint}`;
> const response = await fetchWithRetries(
>     endpoint,
>     { method: 'GET', headers: { ... }, cache: 'no-store' },
>     config.timeoutMs
> );
> ```
> 
> The LearnWorlds API paginates list endpoints using `page` (1-based) and `per_page` query parameters, returning results in a `data` array. The code's `parseResponsePayload()` already handles the `data` array wrapper, which is consistent with this format, but without a pagination loop, everything beyond the first page is silently dropped. There's no indication in the response or the sync run record that data was missed.
> 
> For a data pipeline feeding a recommendation engine (IC-13, #99), silent data loss is a serious concern. I'd suggest either implementing a pagination loop or, at minimum, documenting this as a known limitation with a `// TODO` and a follow-up issue so it doesn't get lost.

Appreciate the detailed write-up and concrete suggestions @bofengb . I implemented the exact direction:

- Added `rawCount` to `LearnworldsFetchResponse` in `types.ts`
- Propagated `rawCount` from parsed payload in `client.ts`
- Updated ingestion metrics in `ingestion.ts` to compute true `invalidRecords`
- Implemented pagination in `client.ts` with explicit safety limits to avoid silent truncation beyond first page

**Review by JBishopCode — APPROVED** [review]
Hey! Thanks for putting this together. The OAuth2 flow, retry/backoff logic, HTTPS enforcement, and error class separation are all well done. The feedback from the earlier review rounds has been addressed thoroughly - the raw count propagation, pagination loop, and failure webhook are all implemented correctly in the final file state. Really solid work.

After reviewing the changed files alongside the task requirements and comment thread, here's where things stand.

---

## 1. What's Been Addressed

All feedback from the review rounds has been resolved:

- **Record counting** — `rawCount` is now propagated through `LearnworldsFetchResponse` in `types.ts`, and `ingestion.ts` correctly computes `invalidRecords = totalRecords - validRecords` rather than hardcoding `0`
- **Pagination** — `client.ts` implements a full pagination loop with `page` + `per_page` params, a stop-on-short-page condition, and a `maxPages` safety guard to prevent silent truncation
- **Failure visibility** — `ingestion.ts` adds a best-effort webhook notification on failed ingestion runs, configurable via `LEARNWORLDS_FAILURE_WEBHOOK_URL` and `LEARNWORLDS_FAILURE_NOTIFY_TIMEOUT_MS`, with a safe no-op default when unconfigured
- **`delete-test-user.ts` typing** — The `any` type on the user find has been replaced with a typed `AdminUserSummary` interface and a proper array check

---

## 2. Summary

1. ✅ OAuth2 auth flow implemented correctly
2. ✅ HTTPS enforcement and config validation in place
3. ✅ Retry/backoff logic handles transient failures and rate limiting
4. ✅ Raw count propagation and invalid record tracking fixed
5. ✅ Pagination loop implemented with safety guard
6. ✅ Failure webhook notification added
7. ✅ Test utility typing cleaned up
8. ✅ Playwright tests cover endpoint auth and validation behavior

This is ready to merge.
